### PR TITLE
Add setVolumes method to replication controller

### PR DESCRIPTION
**Pull request by lulf**

### CODE REVIEW

**Comment by jcantrill** [comment]
[test]

On Thursday, June 30, 2016, Ulf Lilleengen <notifications@github.com> wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/openshift/openshift-restclient-java/pull/183
> Commit Summary
>
>    - Add setVolumes method to replication controller
>
> File Changes
>
>    - *M*
>    src/main/java/com/openshift/internal/restclient/model/ReplicationController.java
>    <https://github.com/openshift/openshift-restclient-java/pull/183/files#diff-0>
>    (10)
>    - *M*
>    src/main/java/com/openshift/restclient/model/IReplicationController.java
>    <https://github.com/openshift/openshift-restclient-java/pull/183/files#diff-1>
>    (8)
>    - *M*
>    src/test/java/com/openshift/internal/restclient/model/v1/ReplicationControllerTest.java
>    <https://github.com/openshift/openshift-restclient-java/pull/183/files#diff-2>
>    (19)
>
> Patch Links:
>
>    - https://github.com/openshift/openshift-restclient-java/pull/183.patch
>    - https://github.com/openshift/openshift-restclient-java/pull/183.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift/openshift-restclient-java/pull/183>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AEVnOC7_2CiIBNYP1VTpnWFwjOF7uhP5ks5qQ7nwgaJpZM4JCHj7>
> .
>


-- 
--
Jeff Cantrill
Senior Software Engineer, Red Hat Engineering
OpenShift Integration Services
Red Hat, Inc.
*Office*: 703-748-4420 | 866-546-8970 ext. 8162420
jcantril@redhat.com
http://www.redhat.com

**Comment by jcantrill** [comment]
[merge]

On Thu, Jun 30, 2016 at 9:21 PM, OpenShift Bot <notifications@github.com>
wrote:

> Java Client Test Results: SUCCESS (
> https://ci.openshift.redhat.com/jenkins/job/test-openshift-restclient-java/161/
> )
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift/openshift-restclient-java/pull/183#issuecomment-229831592>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEVnODKf416WlEigXypYmXzIbqvWUIxzks5qRGuHgaJpZM4JCHj7>
> .
>



-- 
--
Jeff Cantrill
Senior Software Engineer, Red Hat Engineering
OpenShift Integration Services
Red Hat, Inc.
*Office*: 703-748-4420 | 866-546-8970 ext. 8162420
jcantril@redhat.com
http://www.redhat.com

**Comment by lulf** [comment]
@jcantrill Thanks! When do you think we can expect to see this part of a tag to build against?

**Comment by jcantrill** [comment]
@lulf I would not expect it to be in any final release for a while.  We will be bumping master to 5.0.x soon because of a refactoring of the underlying http client.  I could generate a 4.1.0 final if you need it before that work.  It will otherwise be rolled into the 5.0.x stream

**Comment by lulf** [comment]
@jcantrill A 4.1.0 would be great, as we are starting to accumulate a lot of changes that depends on these new APIs, and we currently await merging them to avoid breaking our CI pipeline.

**Comment by jcantrill** [comment]
Do they need to be in a FINAL for your purposes or is SNAPSHOT sufficient?
I can deploy the later right now if you need it.

On Tue, Jul 5, 2016 at 9:08 AM, Ulf Lilleengen <notifications@github.com>
wrote:

> @jcantrill <https://github.com/jcantrill> A 4.1.0 would be great, as we
> are starting to accumulate a lot of changes that depends on these new APIs,
> and we currently await merging them to avoid breaking our CI pipeline.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift/openshift-restclient-java/pull/183#issuecomment-230473137>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEVnODZVUojl_iQn5GdLMOjPEPzcR5cpks5qSldfgaJpZM4JCHj7>
> .
>



-- 
--
Jeff Cantrill
Senior Software Engineer, Red Hat Engineering
OpenShift Integration Services
Red Hat, Inc.
*Office*: 703-748-4420 | 866-546-8970 ext. 8162420
jcantril@redhat.com
http://www.redhat.com

**Comment by lulf** [comment]
@jcantrill Snapshot should be good for now. I can add the snapshot repo to our build settings.

**Pull request merged**
