### PR TITLE
Add setTagWithImagId function into ImageStream model

### PR DESCRIPTION
**Pull request by EtienneCoutaud**
Hi folks, this PR adds the feature to tag an image into an imageStream using a reference to a image name. It behaves like the tag process using OpenShift CLI.

### CODE REVIEW

**Comment by gabemontero** [comment]
fyi @jcantrill I was looking at a very similar change for a separate item I'm working on.

**Comment by jcantrill** [comment]
@EtienneCoutaud @gabemontero  does this PR accomplish similiar functionality? https://github.com/openshift/openshift-restclient-java/pull/113  Its been pending awaiting a review from @adietish but I can merge it if needed

**Comment by gabemontero** [comment]
@jcantrill @EtienneCoutaud @adietish yep, it does look like it accomplishes the same thing; and I think it surfaces the capability through the API in a better way.

If @adietish can review in a few days I don't mind waiting, but if we are talking a week or two, yes, please go ahead and merge.

**Comment by jcantrill** [comment]
closing in favor of https://github.com/openshift/openshift-restclient-java/pull/113

**Pull request closed without merging**
