### PR TITLE
[373] silence errors when determining master version

### LINKED ISSUE #373: NotFoundException on thread "OkHttp Dispatcher"
Hi!
I have a basic code that creates a client and lists the pods like the following:

```
String url = "https://192.168.34.42:8443";
String projectName = "myproject";
String bearerToken = "<The Token>";
IClient client = new ClientBuilder(url).usingToken(bearerToken).build();
List<IPod> pods = client.list(ResourceKind.POD, projectName);
pods.forEach(p -> System.out.println(p.getName()));
```
The point is that the code works fine, but on the console I get the following exception:
```
Exception in thread "OkHttp Dispatcher" com.openshift.restclient.NotFoundException:  
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.createOpenShiftException(ResponseCodeInterceptor.java:113)
	at com.openshift.internal.restclient.okhttp.ResponseCodeInterceptor.intercept(ResponseCodeInterceptor.java:66)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Inside `ResponseCodeInterceptor.intercept` the local response is `Response{protocol=http/1.1, code=404, message=Not Found, url=https://192.168.34.42:8443/version/openshift}`.

I am using minishift v1.32.0+009893b and openshift-restclient-java-7.0.0.Final on a Windows 10 machine with jdk8u191.

Thanks for your work.

### PR DESCRIPTION
**Pull request by Ladicek**
Resolves #373

### CODE REVIEW

**Comment by adietish** [comment]
@Ladicek great contribution. Would you mind also adding a unit-test? ex. mock the response with 404 and 200 and assert that the versionsetter reacts accordingly?

**Comment by Ladicek** [comment]
Added tests as requested :-)

**Comment by adietish** [comment]
@Ladicek awesomeness, thx!

**Comment by adietish** [comment]
deployed openshift-restclient-java 7.1.1-SNAPSHOT to repository.jboss.org.

**Comment by Ladicek** [comment]
Thanks!

**Pull request merged**
