### PR TITLE
allow configuration of ping interval and its time unit for OkHttpClie…

### LINKED ISSUE #374: Allow configuration of ping interval for OkHttpClient via ClientBuilder
The latest versions of OkHttpClient lib support the configuration of ping interval for websockets, but ClientBuilder API does not allow to specify ping interval. 
By default ping interval = 0, which means that no ping is performed by default. As the result websocket connection gets teared down by server and all registered IWatchers have to be reconnected and as side effect they load (on com.openshift.restclient.IOpenShiftWatchListener#connected event) all resources they are configured to watch for.
With non zero ping interval the connection can be keept alive.

### PR DESCRIPTION
**Pull request by denisanfimov**
Closes #374

### CODE REVIEW

**Comment by adietish** [comment]
@denisanfimov thx for pointing this out and even providing a PR. Awesome!
Given that we change the API we might want to bump the minor version 7.0.1->7.1.0. Agree?

**Comment by denisanfimov** [comment]
Hello, André!
Thanks for quick response.
As for minor version change, yes I agree with you.

**Comment by adietish** [comment]
@denisanfimov ok great, can you add this change please? Imho better than me bumping and then you rebasing.

**Comment by denisanfimov** [comment]
done

**Comment by adietish** [comment]
@denisanfimov great, thx!

**Comment by adietish** [comment]
@denisanfimov deployed openshift-restclient-java 7.1.0-SNAPSHOT to the maven repository. Thanks!

**Pull request merged**
