### PR TITLE
[OSJC-282] - Check Java9 compatibility

### PR DESCRIPTION
**Pull request by jeffmaury**
Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by adietish** [comment]
[merge]

**Comment by adietish** [comment]
[test]

**Comment by adietish** [comment]
@jeffmaury no idea why CI fails, i have it running just fine locally:
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 9.0.4, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.227 s
[INFO] Finished at: 2018-02-16T15:02:13+01:00
[INFO] Final Memory: 24M/82M
```

**Comment by adietish** [comment]
[merge]

**Comment by adietish** [comment]
@jcantrill jenkins merge-job is complaining about an outdated maven version:
```
Started by remote host 50.17.198.52
[EnvInject] - Loading node environment variables.
Building in workspace /var/lib/jenkins/jobs/test-openshift-restclient-java/workspace
[workspace] $ /bin/sh -xe /tmp/jenkins1326881853492415982.sh
+ export JAVA_HOME=/usr/lib/jvm/java-1.8.0
+ JAVA_HOME=/usr/lib/jvm/java-1.8.0
+ export MAVEN_HOME=/usr/share/maven
+ MAVEN_HOME=/usr/share/maven
+ /usr/share/maven/bin/mvn -version
Apache Maven 3.0.5 (Red Hat 3.0.5-17)
...
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-maven-version) @ openshift-restclient-java ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
To build this project Maven 3.2.5 (or greater) is required. Please install it.
```
I cannot log into jenkins and configure it. Who can install a newer maven version in jenkins?

**Comment by adietish** [comment]
@jeffmaury I bet the enforcer rule that requires maven 3.2.5 was included via the bump in the parent pom that you executed. Correct?

**Comment by jeffmaury** [comment]
@adietish  yes I will roll back and override and maven enforcer plugin version

**Comment by adietish** [comment]
@jcantrill can we please grant merge rights to @jeffmaury?

**Comment by adietish** [comment]
[merge]

**Comment by adietish** [comment]
[merge]

**Pull request merged**
