### PR TITLE
Add read support for ConfigMap resource

### PR DESCRIPTION
**Pull request by lulf**
@jcantrill I will probably work to add write functionality as well if I need it.

### CODE REVIEW

**Comment by adietish** [comment]
thanks for the contrib!
Would be even greater if you could add some unit tests, please?

**Comment by lulf** [comment]
@adietish I added one src/test/java/com/openshift/internal/restclient/model/v1/ConfigMapTest.java after comments on my previous pull-request. Should I add another one? I think the test covers the current functionality of the ConfigMap.

**Comment by adietish** [comment]
@lulf oh, missed those. Sorry, all fine then!

**Comment by adietish** [comment]
[test]

**Comment by jcantrill** [comment]
[merge]

**Pull request merged**
