### PR TITLE
Allow setting IBuildSource on BuildConfig

### PR DESCRIPTION
**Pull request by aslakknutsen**

### CODE REVIEW

**Comment by jcantrill** [comment]
@aslakknutsen any 'set' tests you can add?

**Comment by aslakknutsen** [comment]
@jcantrill yea, it was waiting for #21 

It's force pushed here: https://github.com/aslakknutsen/openshift-restclient-java/commit/b5da0194eaf0590735e582dc8889e02cf88606ed#diff-533fdb8bb05aaa46df52c72db00ed93dR94

**Comment by aslakknutsen** [comment]
Good to go :+1:

**Comment by jcantrill** [comment]
cc @aslakknutsen merged

**Pull request merged**
