### PR TITLE
[OSJC-194] implemented Template#isMatching(String)

### PR DESCRIPTION
**Pull request by adietish**
Moving from JBT to client lib as discussed here: https://github.com/jbosstools/jbosstools-openshift/pull/691/files#diff-b5469f1a64ca531f5d6a529b1236aaecR51

### CODE REVIEW

**Comment by adietish** [comment]
[test]

**Comment by adietish** [comment]
@jcantrill pls review

**Comment by jcantrill** [comment]
@adietish LGTM....aside from the compilation failure :)

**Comment by adietish** [comment]
[merge]

**Comment by adietish** [comment]
[merge]

**Comment by adietish** [comment]
[merge]

**Pull request merged**
