### PR TITLE
[363] dont send resource in payload when DefaultClient#delete(IResource)

### LINKED ISSUE #363: DefaultClient#delete(IResource) causes endpoint to "500 Internal Server Error"
When calling ```DefaultClient#delete(IResource)``` with a pod resource (or any other resource) results in using "500 internal server error":
```500 no kind "Pod" is registered for version "v1" in scheme "k8s.io/apimachinery/pkg/apis/meta/internalversion/register.go:31"```

This bug was introduced with the change for the following openshift-restclient-java issue: https://github.com/openshift/openshift-restclient-java/issues/359

Further details can be found in the OpenShift plugin for Eclipse: https://issues.jboss.org/browse/JBIDE-26550

### PR DESCRIPTION
**Pull request by adietish**
fixes #363

### CODE REVIEW

**Comment by adietish** [comment]
@jcantrill this PR prevents DefaultClient#delete(IResource) from sending the resource as payload which causes the error depicted in https://issues.jboss.org/browse/JBIDE-26550

**Comment by adietish** [comment]
[merge]

**Comment by jeffmaury** [comment]
[merge]

**Pull request merged**
