### PR TITLE
support multiple certs for SSL connection

### PR DESCRIPTION
**Pull request by gabemontero**
@jcantrill PTAL

@bparees FYI

### CODE REVIEW

**Comment by gabemontero** [comment]
thanks @jcantrill !  When this is merged, any idea how soon afterward a FINAL version could be cut and the maven repo's updated ?

**Comment by jcantrill** [comment]
[merge]

**Comment by jcantrill** [comment]
@adietish  are you guys in a place where a FINAL can be published for this?

**Comment by gabemontero** [comment]
Not sure I understand the merge failure ... it seem to complain at the very end:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.146s
[INFO] Finished at: Wed Jun 14 15:23:36 EDT 2017
[INFO] Final Memory: 22M/453M
[INFO] ------------------------------------------------------------------------
+ RESULT=0
+ set -e
+ popd
~/jobs/test-openshift-restclient-java/workspace
+ '[' 0 -ne 0 ']'
+ true
+ test_pull_requests --merge_pull_request 275 --repo openshift-restclient-java --config /var/lib/jenkins/.test_pull_requests_java_client.json
Rate limit remaining: 2186
  Merging pull request #275 for repo 'openshift-restclient-java'
  Test merging pull request #275 for repo 'openshift-restclient-java'
/bin/test_pull_requests:855:in `test_merge_pull_request': Missing 'Java Client Merge Results:' comment! (RuntimeError)
	from /bin/test_pull_requests:791:in `merge_pull_request'
	from /bin/test_pull_requests:2359:in `<main>'
Build step 'Execute shell' marked build as failure
Recording test results
[description-setter] Description set: <a href="https://github.com/openshift/openshift-restclient-java/pull/275">https://github.com/openshift/openshift-restclient-java/pull/275</a>
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Finished: FAILURE
```

I don't *think* it is related to my change - but of course educate me as needed.

**Comment by gabemontero** [comment]
bump @jcantrill - if the merge failure was the result of my change I'm missing it.  Help?

**Comment by jcantrill** [comment]
[merge][severity:bug]

**Comment by gabemontero** [comment]
Hmm ... same results as before.  All the tests pass, and when it attempts to merge, it complains about a missing comment:

```
+ test_pull_requests --merge_pull_request 275 --repo openshift-restclient-java --config /var/lib/jenkins/.test_pull_requests_java_client.json
Rate limit remaining: 2199
  Merging pull request #275 for repo 'openshift-restclient-java'
  Test merging pull request #275 for repo 'openshift-restclient-java'
/bin/test_pull_requests:872:in `test_merge_pull_request': Missing 'Java Client Merge Results:' comment! (RuntimeError)
	from /bin/test_pull_requests:800:in `merge_pull_request'
	from /bin/test_pull_requests:2401:in `<main>'
Build step 'Execute shell' marked build as failure

```

I think this ci job and the pr tester must be somehow out of sync.  @dobbymoodge - any chance you could take a look / assist ?

**Comment by gabemontero** [comment]
Looks like the last job that passed was May 22.  My guess is whatever disconnect that has occurred started after that.

**Comment by dobbymoodge** [comment]
I'll take a look in a bit, waiting on a bus right now. @stevekuznetsov,
maybe the test prefix string has changed?

**Comment by stevekuznetsov** [comment]
Yeah, there was a misconfiguration for Rosie. I've updated the job.

**Comment by gabemontero** [comment]
thanks @stevekuznetsov @dobbymoodge 

@jcantrill - can you post the merge comment one more time please?

**Comment by dobbymoodge** [comment]
[merge]

**Comment by gabemontero** [comment]
@jcantrill - in case it got lost in the shuffle, would it be ok to cut a 5.7.0-FINAL for this change ?

**Comment by jcantrill** [comment]
@gabemontero published

**Comment by gabemontero** [comment]
@jcantrill looks like maybe something happened with the publish ... I'm not seeing a 5.7.0-Final at either http://repository.jboss.org/nexus/content/groups/public/com/openshift/openshift-restclient-java/ or https://repository.jboss.org/nexus/content/repositories/releases/com/openshift/openshift-restclient-java/ and when I try to reference it as a dependency in the pom.xml maven can't find it.

Is there a new repository I should be referencing, or did the publish flake out ?

thanks

**Comment by gabemontero** [comment]
5.7.0-Final is still missing, but 5.8.0-SNAPSHOT works - we'll go with that  ... thanks again

**Pull request merged**
