### PR TITLE
[OSJC-218] Refactor URLBuilder to remove typemap for kind pluralization

### PR DESCRIPTION
**Pull request by jcantrill**
cc @fbricon @adietish

### CODE REVIEW

**Comment by adietish** [comment]
nice, removes the duplication!
I think though that we should add tests for ResourceKind#pluralize?

**Comment by jcantrill** [comment]
@adietish slave driver!

**Comment by jcantrill** [comment]
[test]

**Comment by jcantrill** [comment]
[merge]

**Comment by jcantrill** [comment]
[merge]

**Pull request merged**
