### PR TITLE
[JBIDE-26172] corrected request url when using api groups

### PR DESCRIPTION
**Pull request by adietish**
[test]

### CODE REVIEW

**Comment by jcantrill** [comment]
@adietish test please?

**Comment by adietish** [comment]
[test]

**Comment by adietish** [comment]
I manually tested this in JBDS with

I tested it with

OpenShift Online which is 3.10.9
api.engint.openshift.com which is 3.7.23
open.paas.redhat.com which is 3.9.31

**Comment by adietish** [comment]
@jcantrill let's go?

**Comment by adietish** [comment]
[merge]

**Comment by adietish** [comment]
@jcantrill @jeffmaury big thanks for your assistance! Saves my/our day!

**Pull request merged**
