### PR TITLE
[OSJC-250] add support for --delete in rsync

### PR DESCRIPTION
**Pull request by adietish**

### CODE REVIEW

**Comment by adietish** [comment]
@jcantrill please review

**Comment by adietish** [comment]
@jcantrill I believe that we should move the rsync related flags to its own class, they're currently in the global space

**Comment by jcantrill** [comment]
@adietish your suggestion seems reasonable to me.  The PR LGTM.  [test]  I will defer to you for merge if you want to make other changes.

**Comment by adietish** [comment]
[merge]

**Pull request merged**
