### PR TITLE
jbide 24539: User should be able to see what OpenShift version a connection is

### PR DESCRIPTION
**Pull request by bdshadow**
squashed version of https://github.com/openshift/openshift-restclient-java/pull/277. I've made it because of the wrong branch name and wrong jira numbers in the commit comments.

@jcantrill @adietish you can look here now

### CODE REVIEW

**Comment by jcantrill** [comment]
@adietish please merge if you have no objections

**Comment by adietish** [comment]
+1 LGTM

**Comment by adietish** [comment]
[test]

**Comment by adietish** [comment]
[merge]

**Comment by adietish** [comment]
[merge]

**Comment by adietish** [comment]
deployed updated client version 5.7.0-SNAPSHOT to maven repository

**Pull request merged**
