### PR TITLE
impl'd rudimentary support for readiness- and lifeness-probes

### PR DESCRIPTION
**Pull request by adietish**
# DONT MERGE YET, WORK IN PROGRESS

### CODE REVIEW

**Comment by adietish** [comment]
[test]

**Comment by adietish** [comment]
@jcantrill dare to comment? I suspect no big changes ahead before I launch this into master.

**Comment by jcantrill** [comment]
I dont see anything glaring.  One item we might change is to add lint check so we can get away from these annoying diffs when its only spaces.

**Comment by adietish** [comment]
@jcantrill sure, that would help.

**Comment by adietish** [comment]
[merge]

**Pull request merged**
