### PR TITLE
release 9.0.4.Final

### PR DESCRIPTION
**Pull request by adietish**
follows up on https://github.com/openshift/openshift-restclient-java/pull/474

### CODE REVIEW

**Review by jeffmaury — APPROVED** [review]
LGTM

**Comment by adietish** [comment]
@sbouchet released 9.0.4.Final at https://repository.jboss.org/nexus/service/local/repositories/releases/content/com/openshift/openshift-restclient-java/9.0.4.Final/openshift-restclient-java-9.0.4.Final.jar
tagged and bumped master to 9.0.5-SNAPSHOT

**Pull request merged**
