### PR TITLE
Add error param handling for OAuth redirects

### PR DESCRIPTION
**Pull request by liggitt**

### CODE REVIEW

**Comment by liggitt** [comment]
@jcantrill PTAL

**Comment by jcantrill** [comment]
LGTM.  we have the bot hooked up here for both merge and test

**Comment by liggitt** [comment]
I'm getting closer to being able to test

**Comment by liggitt** [comment]
tested, updated to call `createLocationURI` instead of `getLocationURI`, because calling `getLocationURI` twice with the same URI raises a redirect loop exception. If we called it to check stuff, then called the `super` implementation, it would also call `getLocationURI` and think it had hit a redirect loop, rather than following the URI.

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
@jcantrill all set, PTAL

**Comment by liggitt** [comment]
[merge]

**Comment by jcantrill** [comment]
[merge]

**Pull request merged**
