### PR TITLE
fix list returning objects.  It's not a thing

### PR DESCRIPTION
**Pull request by jcantrill**
@jeffmaury @adietish  fix to list that was talked about earlier.  I'm not sure why 'object' was ever in there as I can not find reference to it in the origin code base.

### CODE REVIEW

**Comment by jeffmaury** [comment]
Objects are used in templates, no? So maybe not in that case but you should find it in Origin code

**Comment by jcantrill** [comment]
@jeffmaury objects are used for templates. but this change is for List.  Ran the server template integration test which passes without failure.

**Comment by adietish** [comment]
+1 works for me

**Comment by jcantrill** [comment]
[merge]

**Pull request merged**
