### PR TITLE
Add ability to remove annotations

### PR DESCRIPTION
**Pull request by markpaychex**

### CODE REVIEW

**Comment by jcantrill** [comment]
[test]

**Comment by jcantrill** [comment]
@markpaychex are you able to use the master branch or do you require this fix in 3.1?  We currently don't have any plans to produce a new 3.1 release.

**Comment by markpaychex** [comment]
Hello,
My assumption was that the master branch (version 4.0.0) is for an upcoming OpenShift version 4.0.0 whereas 3.1.x is for OpenShift 3.1.x. Is that assumption incorrect?

**Comment by jcantrill** [comment]
@markpaychex thats not necessarily true as we bumped to 4.0.0 for a breaking api change needed to support the up coming release of the eclipse tooling.  Openshift will be releasing 3.2 shortly  which will be supported by the 4.x client.  The versioning is confusing I admit, but we definitely should patch the master branch.  If you also need a 3.1 release of the client, we can patch it there as well.

**Comment by markpaychex** [comment]
Ok. In that case it can be put into the master branch I think. Thanks.

**Comment by jcantrill** [comment]
Merged and cherry-picked into master

On Tue, Mar 1, 2016 at 1:27 PM, Mark <notifications@github.com> wrote:

> Ok. In that case it can be put into the master branch I think. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/openshift-restclient-java/pull/119#issuecomment-190842729>
> .
>



-- 
--
Jeff Cantrill
Senior Software Engineer, Red Hat Engineering
Red Hat, Inc.
*Office*: 703-748-4420 | 866-546-8970 ext. 8162420
jcantril@redhat.com
http://www.redhat.com

**Pull request merged**
