### PR TITLE
[OSJC-142] merged v2 with v3 packages, removed non-required classes

### PR DESCRIPTION
**Pull request by adietish**

### CODE REVIEW

**Comment by adietish** [comment]
@jcantrill please review!

ps. I think that we should seriously think about dropping the "internal" package, It does not make a lot of sense imho, internal/external should be reflected by appropriate access restrictions as in jdk and other frameworks,

**Comment by adietish** [comment]
@jcantrill please review

ps. we should consider dropping the internal package and merge its contents into the main package.

**Comment by jcantrill** [comment]
@adietish looks good to me....i'm not fond of the 'internal' convention used by osgi either, but it would be nice to make it obvious somehow that some classes are open to change by us and consumers should not use those classes.  lets discuss it further

**Comment by adietish** [comment]
@jcantrill now that we created the new repo as we were told to, do we now have openshift-bot and an integration-build in place?

**Comment by jcantrill** [comment]
Probably not.  I'll speak to Dan M. to see who does that

On 04/10/2015 08:59 AM, André Dietisheim wrote:
> @jcantrill <https://github.com/jcantrill> now that we created the new
> repo as we were told to, do we now have openshift-bot and an
> integration-build in place?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/openshift-restclient-java/pull/5#issuecomment-91546809>.
>

-- 
Jeff Cantrill
Senior Software Engineer, Red Hat Engineering
Red Hat
Office: 703-748-4420 | 866-546-8970 ext. 8162420
jcantril@redhat.com
http://www.redhat.com

**Pull request merged**
